### ISSUE TITLE
Find and document all relevant Resting State open source EEG dataset on OpenNeuro

### ISSUE THREAD

**Issue by yacineMahdid** [BIAPT/Consciousness-Graph#4]
The first goal of your project is to characterize the difference in various ways of constructing a graph of a healthy conscious brain under resting state condition. There are various type of graphs we would want to construct AEC, wPLI, NSTE (and maybe others depending on their popularity, like PLV)) & compare and there is various way of constructing these graph within these types. In order to have a solid foundation for comparison we will need to choose one or many solid dataset of EEG recording. The first step in doing so is to comb the open source dataset for EEG data and characterize them to find out which ones we should choose.

- [x] Go in [OpenNeuro](https://openneuro.org/) and familiarize yourself with the browsing of dataset (420 available)
- [x] Find out all dataset that have EEG recording + healthy participant + resting states conditions
- [x] create a folder named `milestones/0_experiments_preparation/` in this repository
- [x] inside that repository gather the information from these dataset (strongly recommend using a markdown file name README.md) within that folder so that we can directly read the report on Github.
- [x] write a conclusion on the README.md about what you think the best dataset(s) is and why (there is no good answer we will discuss that together anyway)

**Comment by raph-rc** [comment]
I have finished, all the info is in the README.md
